# ==============
# Pre run initialization operations:
# - modify geometry
# - provide verbosity parameters
# - modify physics
# - provide random seed, if needed
# ==============

# Set run verbosity
/run/verbose 1
/control/verbose 0
/control/saveHistory
/run/printProgress 10000
# /run/numberOfThreads 4

# Modify geometry (custom functions)
# /geometry/world/radius 20 cm
# /geometry/target/size 10 mm
# /geometry/target/center 0 0 0 mm
/geometry/target/thickness 3 mm
# /geometry/target/rotation 3 mm
# /geometry/target/material G4_W

# Initialize run
/run/initialize

# ==============
# Post run initialization operations:
# - Visualization
# - Define particle source
# - Define custom analysis (histograms, ntuples)
# - Run
# ==============

# =/=/=/=/= Particle source section =/=/=/=/=

# Set the particle source: must be done after run initialization.
# Particle source must be chosen between e- and gamma (for our use)
/gps/verbose 0
/gps/particle e-

# Particle source spatial information
/gps/pos/type Beam
/gps/pos/centre 0 0 -5 mm
/gps/pos/shape Circle
# The radius parameter defines a central flat plateau
/gps/pos/radius 0 mm
/gps/pos/sigma_r 10 um

# Angular distribution of the beam
# By default angular distribution in centered in -z. We turn it around
/gps/ang/rot1 -1 0 0
/gps/ang/rot2 0 1 0
/gps/ang/type beam1d  
/gps/ang/sigma_r 0.002 rad

# Energy distribution of the beam
/gps/ene/mono 10 GeV
/gps/ene/type Gauss
/gps/ene/sigma 10 MeV

# =/=/=/=/= End particle source section =/=/=/=/=

# =/=/=/=/= Analysis section =/=/=/=/=

# Plotting style
# Should be activated only if G4 is built with Freetype support
# /analysis/plot/setStyle ROOT_default

# If setActivationToAll is false, all the ntuples will not be written
# (faster simulations, but only histograms at the end). Default is true 
/analysis/ntuple/setActivationToAll false

# Histogram list
# 1D
# - 0 Final Energy of primaries
# - 1 Final Energy of positrons
# - 2 Final Energy of electrons
# - 3 Final Energy of photons
# - 4 Initial Energy of primaries
#
# 2D
# - 0 Initial primary transverse distribution
# - 1 Initial primary angle distribution
# - 2 Initial X phase space of primaries
# - 3 Initial Y phase space of primaries
# - 4 Final primary transverse distribution
# - 5 Final electron transverse distribution
# - 6 Final positron transverse distribution
# - 7 Final photon transverse distribution
# - 8 Final primary angle distribution
# - 9 Final electron angle distribution
# - 10 Final positron angle distribution
# - 11 Final photon angle distribution

# Personalization of histograms
# /analysis/h1/set id nbins valMin valMax valUnit (optional) valFcn (optional) valBinScheme (optional)
# Example : /analysis/h1/set 1 100 200 800 MeV
# /analysis/h2/set id xnbins xvalMin xvalMax xvalUnit xvalFcn xvalBinScheme (optional) ynbins yvalMin yvalMax yvalUnit yvalFcn yvalBinScheme (optional)
# Example : /analysis/h2/set 1 100 -5 5 mm none linear 100 -5 5 mm none linear #x-y
# /analysis/h1/setXaxisLog id true/false
# /analysis/h1/setYaxisLog id true/false

/analysis/h1/set 0 200 10 10000 MeV none log
/analysis/h1/set 1 200 10 5000 MeV none log
/analysis/h1/set 2 200 10 5000 MeV none log
/analysis/h1/set 3 200 10 5000 MeV none log

/analysis/h1/setXaxisLog 0 true
/analysis/h1/setXaxisLog 1 true
/analysis/h1/setXaxisLog 2 true
/analysis/h1/setXaxisLog 3 true

/analysis/h2/set 0 50 -20 20 um none linear 50 -20 20 um none linear #x-y
/analysis/h2/set 1 50 -2.5 2.5 mrad none linear 50 -2.5 2.5 mrad none linear #x-y
/analysis/h2/set 7 50 -20 20 um none linear 50 -20 20 um none linear #x-y
/analysis/h2/set 8 50 -20 20 mrad none linear 50 -20 20 mrad none linear #x-y
/analysis/h2/set 9 60 -50 50 mrad none linear 60 -50 50 mrad none linear #x-y
/analysis/h2/set 10 60 -50 50 mrad none linear 60 -50 50 mrad none linear #x-y
/analysis/h2/set 11 100 -1.5 1.5 rad none linear 100 -1.5 1.5 rad none linear #x-y

# =/=/=/=/= End analysis section =/=/=/=/=

## Run
/run/beamOn 200000