# Macro file for the initialization of a simple use case of GRAPPA
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 0
# Initialize kernel
/run/initialize

# Use this open statement to create an OpenGL view:
/vis/open OGL 1280x720-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# Create some custom filters

# Filter on particle momentum
/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 20 MeV 10 GeV

# Filter on particle type (show only electrons and positrons)
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add e+

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
# Axes, scale, etc.
# Simple scale line
/vis/scene/add/scale
# Simple axes: x=red, y=green, z=blue.
/vis/scene/add/axes -10 0 0 2 cm
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false

# Specify view angle:
/vis/viewer/set/viewpoinVector -1 0 0
/vis/viewer/set/projection p
/vis/viewer/set/viewpointThetaPhi 60 30
/vis/viewer/set/lightsVector -1 0 0
#/vis/viewer/zoom 2
#
#=======================================================
# Actual particles

# Particles are available in another script

#=======================================================

/vis/viewer/flush
/run/beamOn 10
#/vis/ogl/export snapshot.pdf