# Copyright 2021-2024
#
# Authors:
# Stanimir Kisyov, Davide Terzani
#
# Creator: Davide Terzani
#
# This file is part of GRAPPA.
#
# License: BSD-3-Clause

# Set run verbosity
/run/verbose 0
/control/verbose 0
/control/saveHistory
/run/printProgress 500000
# /run/numberOfThreads 4

# Modify geometry (custom functions)
# /geometry/world/material G4_AIR
/geometry/world/radius 80 cm
/geometry/absorber/thickness 0.1 mm
/geometry/foil/size 3 cm
# /geometry/foil/center 0 0 0 mm
/geometry/foil/thickness 1.42 cm
# /geometry/foil/rotation 45 deg
/geometry/foil/material G4_Ti

# Fix random seed to have repeatable runs
/random/setSeeds 1 2 3

# Select particles from file

/particlesource/particlesFromFile true


# Introduce the muon pair production from photons and increase artificially its probability
/physics_lists/em/GammaToMuons true
/physics_lists/em/PositronToMuons false
/physics_lists/em/GammaToMuonsFactor 50

# Initialize run
/run/initialize

# ==============
# Post run initialization operations:
# - Visualization
# - Define particle source
# - Define custom analysis (histograms, ntuples)
# - Run
# ==============

# =/=/=/=/= Particle source section =/=/=/=/=
# Select the particle filename and the particle type
/particlesource/setFileName InitialPhaseSpace.dat
/particlesource/setParticle e-
/particlesource/print

# Particle source spatial information (NO NEED SINCE FROM FILE)

# =/=/=/=/= End particle source section =/=/=/=/=

# =/=/=/=/= Analysis section =/=/=/=/=

# Plotting style
# Should be activated only if G4 is built with Freetype support
/analysis/plot/setStyle ROOT_default

# If setActivationToAll is false, all the ntuples will not be written
# (faster simulations, but only histograms at the end). Default is false 
/analysis/h1/setActivationToAll true
/analysis/h1/setPlottingToAll true
/analysis/h2/setActivationToAll true
/analysis/h2/setPlottingToAll true

# Histogram list
# 1D
# - 0 Final Energy of primaries
# - 1 Final Energy of positrons
# - 2 Final Energy of electrons
# - 3 Final Energy of photons
# - 4 Final Energy of pions
# - 5 Final Energy of muons
# - 6 Initial Energy of primaries
# - 7 Final theta of primaries
# - 8 Final theta of electrons
# - 9 Final theta of positrons
# - 10 Final theta of photons
# - 11 Final theta of pions
# - 12 Final theta of muons
# - 13 Final phi of primaries
# - 14 Final phi of electrons
# - 15 Final phi of positrons
# - 16 Final phi of photons
# - 17 Final phi of pions
# - 18 Final phi of muons
#
# 2D
# - 0 Initial primary transverse distribution
# - 1 Initial primary longitudinal distribution
# - 2 Initial primary angle distribution
# - 3 Initial X phase space of primaries
# - 4 Initial Y phase space of primaries
# - 5 Final primary transverse distribution
# - 6 Final electron transverse distribution
# - 7 Final positron transverse distribution
# - 8 Final photon transverse distribution
# - 9 Final pions transverse distribution
# - 10 Final muons transverse distribution
# - 11 Final primary angle distribution
# - 12 Final electron angle distribution
# - 13 Final positron angle distribution
# - 14 Final photon angle distribution
# - 15 Final pions angle distribution
# - 16 Final muons angle distribution

# Personalization of histograms
# /analysis/h1/set id nbins valMin valMax valUnit (optional) valFcn (optional) valBinScheme (optional)
# Example : /analysis/h1/set 1 100 200 800 MeV
# /analysis/h2/set id xnbins xvalMin xvalMax xvalUnit xvalFcn xvalBinScheme (optional) ynbins yvalMin yvalMax yvalUnit yvalFcn yvalBinScheme (optional)
# Example : /analysis/h2/set 1 100 -5 5 mm none linear 100 -5 5 mm none linear #x-y
# /analysis/h1/setXaxisLog id true/false
# /analysis/h1/setYaxisLog id true/false

/analysis/h1/set 0 200 10 1000 MeV none linear
/analysis/h1/set 1 200 10 1000 MeV none linear
/analysis/h1/set 2 200 10 1000 MeV none linear
/analysis/h1/set 3 200 1 100 MeV none linear
/analysis/h1/set 4 200 1 1000 MeV none linear
/analysis/h1/set 5 200 1 1000 MeV none linear
/analysis/h1/set 6 200 10 1000 MeV none linear
/analysis/h1/set 7 200 0. 50 mrad none linear
/analysis/h1/set 8 200 0. 50 mrad none linear
/analysis/h1/set 9 200 0 50 mrad none linear
/analysis/h1/set 10 200 0. 50 mrad none linear
/analysis/h1/set 11 200 0. 50 mrad none linear
/analysis/h1/set 12 200 0. 50 mrad none linear

/analysis/h1/setXaxisLog 0 true
/analysis/h1/setXaxisLog 1 true
/analysis/h1/setXaxisLog 2 true
/analysis/h1/setXaxisLog 3 true
/analysis/h1/setXaxisLog 9 true
/analysis/h1/setXaxisLog 10 true
/analysis/h1/setXaxisLog 11 true
/analysis/h1/setXaxisLog 12 true
/analysis/h1/setXaxisLog 13 true

/analysis/h2/set 0 50 -30 30 um none linear 50 -30 30 um none linear #x-y
/analysis/h2/set 2 50 -30 30 mrad none linear 50 -30 30 mrad none linear #x-y
/analysis/h2/set 3 50 -3 3 um none linear 50 -10 10 MeV none linear #x-y
/analysis/h2/set 4 50 -3 3 um none linear 50 -10 10 MeV none linear #x-y
/analysis/h2/set 4 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 5 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 6 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 7 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 8 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 9 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 10 50 -30 30 mrad none linear 50 -30 30 mrad none linear #x-y
/analysis/h2/set 11 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y
/analysis/h2/set 12 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y
/analysis/h2/set 13 100 -1.5 1.5 rad none linear 100 -1.5 1.5 rad none linear #x-y
/analysis/h2/set 14 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y
/analysis/h2/set 15 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y

# =/=/=/=/= End analysis section =/=/=/=/=

# =/=/=/=/= Ntuple control section =/=/=/=/=

/ntuplecontrol/setDump 0 1

# =/=/=/=/= End Ntuple control section =/=/=/=/=

## Run
#/run/beamOn 30000000
