# Copyright 2021-2026
#
# Authors:
# Stanimir Kisyov, Sarah Schröder, Davide Terzani
#
# Creator: Davide Terzani
#
# This file is part of GRAPPA.
#
# License: BSD-3-Clause

# Select particles from file

/particlesource/particlesFromFile true

# Select the particle filename and the particle type
/particlesource/setFileName InitialPhaseSpace.dat
/particlesource/setParticle e-
/particlesource/print

# Particle source spatial information (NO NEED SINCE FROM FILE)
