# ==============
# Pre run initialization operations:
# - modify geometry
# - provide verbosity parameters
# - modify physics
# - provide random seed, if needed
# ==============

# Set run verbosity
/run/verbose 0
/control/verbose 0
/control/saveHistory
/run/printProgress 500000
# /run/numberOfThreads 4

# Modify geometry (custom functions)
/geometry/world/radius 80 cm
/geometry/target/size 3 cm
# /geometry/target/center 0 0 0 mm
/geometry/target/thickness 1.42 cm
# /geometry/target/rotation 3 mm
/geometry/target/material G4_Ti

# Fix random seed to have repeatable runs
/random/setSeeds 1 2 3

# Select particles from file

/particleSource/ParticlesFromFile true
/particleSource/FileName InitialPhaseSpace.dat

# Initialize run
/run/initialize

# ==============
# Post run initialization operations:
# - Visualization
# - Define particle source
# - Define custom analysis (histograms, ntuples)
# - Run
# ==============

# =/=/=/=/= Particle source section =/=/=/=/=

# Set the particle source: must be done after run initialization.
# Particle source must be chosen between e- and gamma (for our use)

/gun/particle gamma

# Particle source spatial information (NO NEED SINCE FROM FILE)

# =/=/=/=/= End particle source section =/=/=/=/=

# =/=/=/=/= Analysis section =/=/=/=/=

# Plotting style
# Should be activated only if G4 is built with Freetype support
/analysis/plot/setStyle ROOT_default

# If setActivationToAll is false, all the ntuples will not be written
# (faster simulations, but only histograms at the end). Default is false 
/analysis/ntuple/setActivationToAll true
/analysis/h1/setActivationToAll true
/analysis/h1/setPlottingToAll true
/analysis/h2/setActivationToAll true
/analysis/h2/setPlottingToAll true

# Histogram list
# 1D
# - 0 Final Energy of primaries
# - 1 Final Energy of positrons
# - 2 Final Energy of electrons
# - 3 Final Energy of photons
# - 4 Initial Energy of primaries
#
# 2D
# - 0 Initial primary transverse distribution
# - 1 Initial primary angle distribution
# - 2 Initial X phase space of primaries
# - 3 Initial Y phase space of primaries
# - 4 Final primary transverse distribution
# - 5 Final electron transverse distribution
# - 6 Final positron transverse distribution
# - 7 Final photon transverse distribution
# - 8 Final primary angle distribution
# - 9 Final electron angle distribution
# - 10 Final positron angle distribution
# - 11 Final photon angle distribution

# Personalization of histograms
# /analysis/h1/set id nbins valMin valMax valUnit (optional) valFcn (optional) valBinScheme (optional)
# Example : /analysis/h1/set 1 100 200 800 MeV
# /analysis/h2/set id xnbins xvalMin xvalMax xvalUnit xvalFcn xvalBinScheme (optional) ynbins yvalMin yvalMax yvalUnit yvalFcn yvalBinScheme (optional)
# Example : /analysis/h2/set 1 100 -5 5 mm none linear 100 -5 5 mm none linear #x-y
# /analysis/h1/setXaxisLog id true/false
# /analysis/h1/setYaxisLog id true/false

/analysis/h1/set 0 200 10 1000 MeV none log
/analysis/h1/set 1 200 10 1000 MeV none log
/analysis/h1/set 2 200 10 1000 MeV none log
/analysis/h1/set 3 200 1 100 MeV none log
/analysis/h1/set 4 200 10 1000 MeV none log

/analysis/h1/setXaxisLog 0 true
/analysis/h1/setXaxisLog 1 true
/analysis/h1/setXaxisLog 2 true
/analysis/h1/setXaxisLog 3 true
/analysis/h1/setXaxisLog 4 true

/analysis/h2/set 0 50 -3 3 um none linear 50 -3 3 um none linear #x-y
/analysis/h2/set 1 50 -30 30 mrad none linear 50 -30 30 mrad none linear #x-y
/analysis/h2/set 2 50 -3 3 um none linear 50 -10 10 MeV none linear #x-y
/analysis/h2/set 3 50 -3 3 um none linear 50 -10 10 MeV none linear #x-y
/analysis/h2/set 4 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 5 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 6 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 7 50 -20 20 mm none linear 50 -20 20 mm none linear #x-y
/analysis/h2/set 8 50 -30 30 mrad none linear 50 -30 30 mrad none linear #x-y
/analysis/h2/set 9 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y
/analysis/h2/set 10 60 -100 100 mrad none linear 60 -100 100 mrad none linear #x-y
/analysis/h2/set 11 100 -1.5 1.5 rad none linear 100 -1.5 1.5 rad none linear #x-y

# =/=/=/=/= End analysis section =/=/=/=/=

## Run
/run/beamOn 30000000

# =/=/=/=/= Call visualization script =/=/=/=/=

# Disable analysis before visualization script to avoid
# ovverriding the past analysis. ONLY if enabled before.
/analysis/ntuple/setActivationToAll false
/analysis/h1/setActivationToAll false
/analysis/h1/setPlottingToAll false
/analysis/h2/setActivationToAll false
/analysis/h2/setPlottingToAll false

/control/execute example_vis.mac
# =/=/=/=/= End visualization script =/=/=/=/=