# Copyright 2021-2026
#
# Authors:
# Stanimir Kisyov, Sarah Schröder, Davide Terzani
#
# Creator: Davide Terzani
#
# This file is part of GRAPPA.
#
# License: BSD-3-Clause

/control/verbose 2
/run/verbose 0

# Introduce the muon pair production from photons and increase artificially its probability
/GRAPPA/physicsList/setMuonPairCrossSectionFactor 200
/GRAPPA/physicsList/setBiasing true
/GRAPPA/physicsList/list

# Modify geometry (custom functions)
/geometry/useGDML true
/geometry/gdmlFile geometry/multiple_foils.gdml
/geometry/dumpObjGeometry true
/geometry/objDumpDirectory solids
# The following sets the target when GDML is not used
#/control/execute set_geometry.mac

# Initialize kernel
/run/initialize

# Use this open statement to create an OpenGL view:
/vis/open OGL 640x480-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume

# Uncomment if trajectories are desired
# /control/execute draw_trajectories.mac

# Axes, scale, etc.
# Simple scale line
/vis/scene/add/scale 5 cm z 0 0 1 manual -10 0 -2 cm
# Simple axes: x=red, y=green, z=blue.
/vis/scene/add/axes -10 0 0 2 cm
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility WorldLogical 0 false
/vis/geometry/set/visibility AbsorberLogical 0 false

# Remove hidden edges
/vis/viewer/set/hiddenEdge 1
# Specify view angle:
#/vis/viewer/set/projection p
/vis/viewer/set/targetPoint 0 0 0 cm
/vis/viewer/set/viewpointThetaPhi 60 8
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/zoom 2.3

# The GPS source is not set in this file
# please select a source using the GPS commands.
# The goal of this script is only to initialize the visualization

/analysis/setFileName Data_output_vis
