name: Check code style

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-style:
    name: Check code style with clang-format
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install clang-format
        run: |
          echo "Updating packages and getting the llvm repo"
          wget https://apt.llvm.org/llvm.sh
          sudo apt-get update
          chmod u+x llvm.sh
          sudo ./llvm.sh 18 all
          echo "The basic installed version of clang-format is $(clang-format --version)"
          echo "The installed version of clang-format-18 is $(clang-format-18 --version)"
          sudo update-alternatives --remove-all clang-format
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 18
          echo "default clang-format has been updated to $(clang-format --version)"
      - name: Run clang-format
        run: |
          find src/ include/ scripts/ \
          -type f -name "*.hpp" -o \
          -type f -name "*.cpp" -o \
          -type f -name "*.C.in" -o \
          -type f -name "*.h.in" | xargs clang-format --style=file --dry-run --Werror
