name: MacOs compilation

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - src/**
      - include/**
      - CMakeLists.txt
      - scripts/CMakeLists.txt
      - .github/workflows/macos_test.yml
  push:
    branches:
      - dev
    paths:
      - src/**
      - include/**
      - CMakeLists.txt
      - scripts/CMakeLists.txt
      - .github/workflows/macos_test.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPENDENCY_INSTALL: ${{ github.workspace }}/dependency_install
  GEANT4_BINARY_URL: https://cern.ch/geant4-data/releases/lib4.11.3.p02/Darwin-clang17.0.0-Sequoia.tar.gz

jobs:
  dependency-install:
    # Run on push OR on a non‑draft PR
    if: ${{ github.event_name != 'pull_request' ||
           (github.event_name == 'pull_request' && github.event.pull_request.draft == false) }}
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Cache Geant4 Install
        id: geant4-cache
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 0
        with:
          # The directory where Geant4 will be installed (in this example: geant4-install).
          path: ${{ env.DEPENDENCY_INSTALL }}/geant4-install
          # Use a key that matches your Geant4 version, OS, and potentially other environment variables.
          key: ${{ runner.os }}-geant4-v11.3.2-precompiled-${{ env.CACHE_NUMBER }}

      - name: Download and Install Geant4 Binaries
        if: steps.geant4-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.DEPENDENCY_INSTALL }}
          cd ${{ env.DEPENDENCY_INSTALL }}
          echo "Downloading Geant4 pre-compiled binaries..."
          curl -L -o geant4-binaries.tar.gz ${{ env.GEANT4_BINARY_URL }}
          echo "Extracting Geant4 binaries..."
          tar -xzvf geant4-binaries.tar.gz
          mv Geant4-* geant4-install
          rm geant4-binaries.tar.gz
          echo "Geant4 binaries installed successfully"

  build-and-test:
    needs: dependency-install
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -e {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Geant4 Install
        uses: actions/cache/restore@v4
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 0
        with:
          # The directory where Geant4 will be installed (in this example: geant4-install).
          path: ${{ env.DEPENDENCY_INSTALL }}/geant4-install
          # Use a key that matches your Geant4 version, OS, and potentially other environment variables.
          key: ${{ runner.os }}-geant4-v11.3.2-precompiled-${{ env.CACHE_NUMBER }}

      - name: Install Build tools
        run: |
          set +e
          echo "Updating packages"
          brew update
          brew upgrade || true
          echo "Installing requisites"
          brew install cmake llvm

      - name: Compile Project
          # Temporarily ignore deprecated classes
        run: |
          export CXXFLAGS="-Wall -Wextra -Werror -Wpedantic -Wshadow -Wno-deprecated-declarations"

          cmake -S . -B build --log-level=VERBOSE \
            -DCMAKE_BUILD_TYPE=Release \
            -DGeant4_DIR=${{ env.DEPENDENCY_INSTALL }}/geant4-install/lib/cmake/Geant4 \
            -DCMAKE_INSTALL_PREFIX=.
          cmake --build build --target install -j 2
