name: Ubuntu compilation

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]
    paths:
      - src/**
      - include/**
      - CMakeLists.txt
      - scripts/CMakeLists.txt
      - .github/workflows/ubuntu_test.yml
  push:
    branches:
      - dev
    paths:
      - src/**
      - include/**
      - CMakeLists.txt
      - scripts/CMakeLists.txt
      - .github/workflows/ubuntu_test.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPENDENCY_INSTALL: ${{ github.workspace }}/dependency_install
  GEANT4_BINARY_URL: https://cern.ch/geant4-data/releases/lib4.11.3.p02/Linux-g++11.5.0-Alma9.tar.gz

jobs:
  dependency-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Cache Geant4 Install
        id: geant4-cache
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 0
        with:
          path: ${{ env.DEPENDENCY_INSTALL }}/geant4-install
          key: ${{ runner.os }}-geant4-v11.3.2-precompiled-${{ env.CACHE_NUMBER }}

      - name: Download and Install Geant4 Binaries
        if: steps.geant4-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.DEPENDENCY_INSTALL }}
          cd ${{ env.DEPENDENCY_INSTALL }}
          echo "Downloading Geant4 pre-compiled binaries..."
          curl -L -o geant4-binaries.tar.gz ${{ env.GEANT4_BINARY_URL }}
          echo "Extracting Geant4 binaries..."
          echo "Unix version of Geant4 is distributed without a parent folder, which we create."
          mkdir -p geant4-install
          tar -xzvf geant4-binaries.tar.gz -C geant4-install
          rm geant4-binaries.tar.gz
          echo "Geant4 binaries installed successfully"

  build-and-test:
    needs: dependency-install
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Geant4 Install
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 0
        with:
          # The directory where Geant4 will be installed (in this example: geant4-install).
          path: ${{ env.DEPENDENCY_INSTALL }}/geant4-install
          # Use a key that matches your Geant4 version, OS, and potentially other environment variables.
          key: ${{ runner.os }}-geant4-v11.3.2-precompiled-${{ env.CACHE_NUMBER }}

      - name: Install Build tools
        run: |
          echo "Updating packages"
          sudo apt-get update
          echo "Installing requisites"
          sudo apt-get install -y cmake gcc g++ libx11-dev libxpm-dev libxft-dev libxext-dev libxmu-dev libxerces-c-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Compile Project
        run: |
          export CXXFLAGS="-Wall -Wextra -Werror -Wpedantic -Wshadow"

          cmake -S . -B build --log-level=VERBOSE \
            -DCMAKE_BUILD_TYPE=Release \
            -DGeant4_DIR=${{ env.DEPENDENCY_INSTALL }}/geant4-install/lib64/cmake/Geant4 \
            -DCMAKE_INSTALL_PREFIX=.
          cmake --build build --target install -j 2
